{{- if and .Values.common.secretKey.createSecret (empty .Values.common.secretKey.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyades.secretKeySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.commonLabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
type: Opaque
data:
  secret.key: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
