---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "vulnAnalyzerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vulnAnalyzerSelectorLabels" . }}
spec:
  serviceName: {{ include "vulnAnalyzerName" . }}
  replicas: {{ .Values.vulnAnalyzer.replicas }}
  selector:
    matchLabels:
      {{- include "vulnAnalyzerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vulnAnalyzerSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.common.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "vulnAnalyzerName" . }}
        image: {{ include "vulnAnalyzerImage" . }}
        imagePullPolicy: {{ .Values.vulnAnalyzer.image.pullPolicy }}
        resources:
          {{- toYaml .Values.vulnAnalyzer.resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ include "vulnAnalyzerName" . }}
        ports:
        - name: web
          containerPort: 8092
          protocol: TCP
        volumeMounts:
        - name: kafka-streams-state
          mountPath: /tmp/kafka-streams
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 8092
            path: /q/health/live
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: 8092
            path: /q/health/ready
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
      {{- if not .Values.vulnAnalyzer.persistentVolume.enabled }}
      volumes:
      - name: kafka-streams-state
        emptyDir: { }
      {{- end }}
  {{- if .Values.vulnAnalyzer.persistentVolume.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: kafka-streams-state
    spec:
      storageClassName: {{ .Values.vulnAnalyzer.persistentVolume.className }}
      resources:
        requests:
          storage: {{ .Values.vulnAnalyzer.persistentVolume.size }}
      accessModes:
      - ReadWriteOnce
  {{- end }}