version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
    time: "05:00"
    timezone: Etc/UTC
- package-ecosystem: docker
  directory: mirror-service/src/main/docker
  schedule:
    interval: daily
    time: "05:00"
    timezone: Etc/UTC
- package-ecosystem: docker
  directory: notification-publisher/src/main/docker
  schedule:
    interval: daily
    time: "05:00"
    timezone: Etc/UTC
- package-ecosystem: docker
  directory: repository-meta-analyzer/src/main/docker
  schedule:
    interval: daily
    time: "05:00"
    timezone: Etc/UTC
- package-ecosystem: docker
  directory: vulnerability-analyzer/src/main/docker
  schedule:
    interval: daily
    time: "05:00"
    timezone: Etc/UTC
- package-ecosystem: github-actions
  directory: /.github/workflows
  schedule:
    interval: daily
    time: "05:00"
    timezone: Etc/UTC
- package-ecosystem: maven
  directory: /
  schedule:
    interval: daily
    time: "05:00"
    timezone: Etc/UTC