---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyades.repoMetaAnalyzerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.repoMetaAnalyzerLabels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: web
  selector: {{- include "hyades.repoMetaAnalyzerSelectorLabels" . | nindent 4 }}