name: Enhancement Request
description: File an enhancement request
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping us in making Hyades better!
        
        **First Look for existing Issues**
        Before you create a new issue, please do a search in [open issues](https://github.com/DependencyTrack/hyades/issues)
        to see if the enhancement request has already been filed.
  - type: textarea
    id: behavior-current
    attributes:
      label: Current Behavior
      description: |-
        Describe the current behavior that you observed.
        Consider providing screenshots, log output, and other supplementary data.
        
        *Files and images can be included via drag and drop into this text field.*
    validations:
      required: true
  - type: textarea
    id: behavior-proposed
    attributes:
      label: Proposed Behavior
      description: >-
        Describe how you expect Hyades to behave instead.
        Please include *why* you want the new behavior.
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have read and understand the [contributing guidelines](https://github.com/DependencyTrack/hyades/blob/main/CONTRIBUTING.md#filing-issues)
          required: true
        - label: I have checked the [existing issues](https://github.com/DependencyTrack/hyades/issues) for whether this enhancement was already requested
          required: true