FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
ARG TARGETARCH
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root --chmod=755 target/$TARGETARCH/*-runner /work/application

EXPOSE 8090
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
