{
 "title": "Metrics-Service",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"metrics-service\"}"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"metrics-service\"}"
    }
   ]
  },
  {
   "title": "JVM Live Threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"metrics-service\"}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_outgoing_byte_total"
    }
   ]
  },
  {
   "title": "JVM Peak Threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{job=\"metrics-service\"}"
    }
   ]
  },
  {
   "title": "Java Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_info_total{job=\"metrics-service\"}",
     "legendFormat": "{{vendor}} {{version}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_admin_client_incoming_byte_total{job=\"metrics-service\"}"
    }
   ]
  },
  {
   "title": "JVM Daemon Threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{job=\"metrics-service\"}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"metrics-service\"}",
     "legendFormat": "Process"
    },
    {
     "expr": "system_cpu_usage{job=\"metrics-service\"}",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{job=\"metrics-service\", area=\"heap\"}",
     "legendFormat": "Heap Usage"
    },
    {
     "expr": "jvm_memory_max_bytes{job=\"metrics-service\", area=\"nonheap\"}",
     "legendFormat": "Non-Heap"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"metrics-service\", area=\"heap\"})",
     "legendFormat": "Heap Size"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"metrics-service\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"metrics-service\"}",
     "legendFormat": "Daemon"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"metrics-service\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Event System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } }
 ]
}