{
 "title": "Mirror Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_stream_alive_stream_threads, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\", job=\"mirror-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Record Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_consumed_total{instance=~\"$instance\", job=\"mirror-service\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_produced_total{instance=~\"$instance\", job=\"mirror-service\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Heartbeat Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_heartbeat_rate{instance=~\"$instance\", job=\"mirror-service\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_poll_rate{instance=~\"$instance\", job=\"mirror-service\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Records Polled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_poll_records_avg{instance=~\"$instance\", job=\"mirror-service\"}) by (instance) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Process Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{instance=~\"$instance\", job=\"mirror-service\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Thread Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_process_latency_avg{instance=~\"$instance\",job=\"mirror-service\"}) by (instance) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Punctuate Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_punctuate_total{instance=~\"$instance\", job=\"mirror-service\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Punctuate Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_punctuate_latency_avg{instance=~\"$instance\", job=\"mirror-service\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Request Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_request_total{instance=~\"$instance\", job=\"mirror-service\"}[5m]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Store Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_get_rate{instance=~\"$instance\", job=\"mirror-service\"}) by (in_memory_state_id)",
     "legendFormat": "{{in_memory_state_id}} {{thread_id}}"
    }
   ]
  },
  {
   "title": "State Store Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_put_rate{instance=~\"$instance\", job=\"mirror-service\"}) by (in_memory_state_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Store Delete Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_delete_rate{instance=~\"$instance\", job=\"mirror-service\"}) by (in_memory_state_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}