{
 "title": "Notification Publisher",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_consumer_node_request_rate{client_id=~\".*hyades-notification-publisher.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Cpu Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_memory_rss_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Heap Memory Usage($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"nonheap\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory Usage($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GC Pause Duration($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\"}[1m]) / rate(jvm_gc_pause_seconds_count{instance=~\"$instance\"}[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Memory Allocation Rate($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Streams($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Record Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_manager_records_consumed_rate{instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Response Rate",
   "type": "timeseries",
   "description": "Number of responses received per second",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_response_rate{instance=~\"$instance\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records successfully processed",
   "type": "timeseries",
   "description": "Total number of records successfully processed",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(pc_processed_records_total{instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records failed to process",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(pc_failed_records_total{instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Heartbeat Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_heartbeat_rate{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_time_between_poll_avg{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Outgoing Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_outgoing_byte_total{instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_request_total{instance=~\"$instance\"}[5m]) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}