{
 "title": "Repo Meta Analyzer",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_stream_alive_stream_threads{client_id=~\".*hyades-repository-meta-analyzer.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Cpu Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\", job=\"repo-meta-analyzer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{instance=~\"$instance\", area=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_memory_rss_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Heap Memory Usage($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"nonheap\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory Usage($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"}) by (id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GC Pause Duration($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\"}[1m]) / rate(jvm_gc_pause_seconds_count{instance=~\"$instance\"}[1m]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Memory Allocation Rate($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Connections($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Max Http Connections for all routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_max{instance=~\"$instance\", httpclient=\"hyades-repository-meta-analyzer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Http Connections per route",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_route_max_default{instance=~\"$instance\", httpclient=\"hyades-repository-meta-analyzer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Http connections for all routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_pending{instance=~\"$instance\", httpclient=\"hyades-repository-meta-analyzer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of connections available for all routes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_connections{instance=~\"$instance\", httpclient=\"hyades-repository-meta-analyzer\", state=\"available\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka Streams($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Record Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_consumed_total{instance=~\"$instance\", job=\"repo-meta-analyzer\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_produced_total{instance=~\"$instance\", job=\"repo-meta-analyzer\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Heartbeat Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_heartbeat_rate{instance=~\"$instance\", job=\"repo-meta-analyzer\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_poll_rate{instance=~\"$instance\", job=\"repo-meta-analyzer\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Records Polled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_poll_records_avg{instance=~\"$instance\"}) by (instance) >= 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_stream_thread_poll_records_avg",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Outgoing Byte Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_outgoing_byte_total{instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Stream Alive Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(kafka_stream_alive_stream_threads{instance=~\"$instance\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Process Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Consumer Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_request_total{instance=~\"$instance\"}[5m]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{instance=~\"$instance\", cache=\"metaAnalyzer\"}[1m])) by (result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_puts_total{instance=~\"$instance\", cache=\"metaAnalyzer\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_size{instance=~\"$instance\", cache=\"metaAnalyzer\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}