{
 "title": "Vulnerability Analyzer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_stream_alive_stream_threads, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "System CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Record Consumption Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_consumed_total{instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Record Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_topic_records_produced_total{instance=~\"$instance\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Heartbeat Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_heartbeat_rate{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Poll Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_poll_rate{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Records Polled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_poll_records_avg{instance=~\"$instance\"}) by (instance) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Process Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(kafka_stream_thread_process_total{instance=~\"$instance\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Thread Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_process_latency_avg{instance=~\"$instance\"}) by (instance) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Punctuate Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_thread_punctuate_total{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Punctuate Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_punctuate_latency_avg{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Store Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_get_rate{instance=~\"$instance\"}) by (in_memory_state_id)",
     "legendFormat": "{{in_memory_state_id}} {{thread_id}}"
    }
   ]
  },
  {
   "title": "State Store Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_put_rate{instance=~\"$instance\"}) by (in_memory_state_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Store Delete Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_delete_rate{instance=~\"$instance\"}) by (in_memory_state_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internal Analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Components Scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scanner_components_scanned_total{instance=~\"$instance\",scanner=\"internal\"}[1m])) by (result)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(scanner_components_scanned_total{instance=~\"$instance\",scanner=\"internal\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 57 },
   "targets": [
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_size{instance=~\"$instance\",cache=\"internalCache\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{instance=~\"$instance\",cache=\"internalCache\"}[1m])) by (result)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_puts_total{instance=~\"$instance\",cache=\"internalCache\"}[1m]))",
     "legendFormat": "Puts"
    }
   ]
  },
  { "title": "OSS Index Analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Records Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_processor_records_consumed_total{instance=~\"$instance\",processor=\"OssIndexProcessor\"}[1m])) without (thread_id, instance, task_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_client_requests_seconds_sum{instance=~\"$instance\",clientName=\"ossindex.sonatype.org\"}[1m])) by (clientName) / sum(rate(http_client_requests_seconds_count{instance=~\"$instance\",clientName=\"ossindex.sonatype.org\"}[1m])) by (clientName) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_size{instance=~\"$instance\",cache=\"ossindex\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Batch Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 73 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(scanner_components_batch_size_sum{instance=~\"$instance\",scanner=\"ossindex\"}[1m])) without (instance, thread_id, task_id) / sum(rate(scanner_components_batch_size_count{instance=~\"$instance\",scanner=\"ossindex\"}[1m])) without (instance, thread_id, task_id) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Components Scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scanner_components_scanned_total{instance=~\"$instance\",scanner=\"ossindex\"}[1m])) by (result)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(scanner_components_scanned_total{instance=~\"$instance\",scanner=\"ossindex\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Batch Store Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 77 },
   "targets": [
    {
     "expr": "sum(kafka_stream_store_entries{instance=~\"$instance\",store=\"ossindex-batch-store\"})",
     "legendFormat": "Entries"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_processor_retries_total{instance=~\"$instance\",processor=\"OssIndexProcessor\"}[1m])) by (status, attempts)",
     "legendFormat": "{{status}} (after {{attempts}} attempts)"
    }
   ]
  },
  {
   "title": "Retry Store Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 85 },
   "targets": [
    {
     "expr": "sum(kafka_stream_store_entries{instance=~\"$instance\",store=\"ossindex-retry-store\"}) >= 0",
     "legendFormat": "Entries"
    }
   ]
  },
  {
   "title": "Cache Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{instance=~\"$instance\",cache=\"ossindex\"}[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Cache Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_puts_total{instance=~\"$instance\",cache=\"ossindex\"}[1m]))",
     "legendFormat": "Puts"
    }
   ]
  },
  { "title": "Snyk Analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Records Consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_processor_records_consumed_total{instance=~\"$instance\",processor=\"SnykProcessor\"}[1m])) without (instance, thread_id, task_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(httpcomponents_httpclient_request_seconds_sum{instance=~\"$instance\", client=\"snykHttpClient\"}[1m])) by (client) / sum(rate(httpcomponents_httpclient_request_seconds_count{instance=~\"$instance\"}[1m])) by (client) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 102 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cache_size{instance=~\"$instance\",cache=\"snyk\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 102 },
   "targets": [
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Components Scanned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(scanner_components_scanned_total{instance=~\"$instance\",scanner=\"snyk\"}[1m])) by (result)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(scanner_components_scanned_total{instance=~\"$instance\",scanner=\"snyk\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 106 },
   "targets": [
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_stream_processor_retries_total{instance=~\"$instance\",processor=~\"SnykProcessor\"}[1m])) without (instance, thread_id, task_id)",
     "legendFormat": "{{status}} (after {{attempts}} attempts)"
    }
   ]
  },
  {
   "title": "Retry Store Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 114 },
   "targets": [
    {
     "expr": "sum(kafka_stream_store_entries{instance=~\"$instance\",store=\"snyk-retry-store\"}) >= 0",
     "legendFormat": "Entries"
    }
   ]
  },
  {
   "title": "Cache Get Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_gets_total{instance=~\"$instance\",cache=\"snyk\"}[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Cache Put Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cache_puts_total{instance=~\"$instance\",cache=\"snyk\"}[1m]))",
     "legendFormat": "Puts"
    }
   ]
  }
 ]
}