apiVersion: v2
name: hyades
version: 0.1.1
type: application
appVersion: 1.0.0-SNAPSHOT
home: https://github.com/DependencyTrack/hyades
maintainers:
- name: nscuro
  email: nscuro@protonmail.com
  url: https://github.com/nscuro
- name: mehab
  email: meha.bhargava@citi.com
  url: https://github.com/mehab
- name: sahibamittal
  email: sahiba.mittal@citi.com
  url: https://github.com/sahibamittal
- name: VithikaS
  email: vithika.shukla@citi.com
  url: https://github.com/VithikaS
