---
common:
  nameOverride: ""
  fullnameOverride: ""
  image:
    registry: ghcr.io
    pullSecrets: [ ]
  database:
    jdbcUrl: ""
    username: ""
    password: ""
  kafka:
    bootstrapServers: ""
    topicPrefix: ""

mirrorService:
  annotations: { }
  replicas: 1
  image:
    repository: dependencytrack/hyades-mirror-service
    tag: latest-native
    pullPolicy: Always
  command: [ ]
  args: [ ]
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  env: [ ]
  envFrom: [ ]

notificationPublisher:
  enabled: true
  annotations: { }
  image:
    repository: dependencytrack/hyades-notification-publisher
    tag: latest-native
    pullPolicy: Always
  command: [ ]
  args: [ ]
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  env: [ ]
  envFrom: [ ]

repoMetaAnalyzer:
  annotations: { }
  replicas: 1
  image:
    repository: dependencytrack/hyades-repository-meta-analyzer
    tag: latest-native
    pullPolicy: Always
  command: [ ]
  args: [ ]
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  env: [ ]
  envFrom: [ ]

vulnAnalyzer:
  annotations: { }
  replicas: 1
  image:
    repository: dependencytrack/hyades-vulnerability-analyzer
    tag: latest-native
    pullPolicy: Always
  command: [ ]
  args: [ ]
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  persistentVolume:
    enabled: false
    className: ""
    size: 2Gi
  env: [ ]
  envFrom: [ ]
