common:
  image:
    registry: ghcr.io
    pullSecrets: []

vulnAnalyzer:
  replicas: 1
  image:
    repository: dependencytrack/hyades-vulnerability-analyzer
    tag: latest-native
    pullPolicy: Always
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 2Gi
  persistentVolume:
    enabled: false
    className: ""
    size: 2Gi
  config:
    KAFKA_BOOTSTRAP_SERVERS: "host.minikube.internal:9093"
    KAFKA_STREAMS_NUM_STREAM_THREADS: "6"
    # STATE_STORE_TYPE: "rocks_db"
    # STATE_STORE_ROCKS_DB_COMPACTION_STYLE: ""
    # STATE_STORE_ROCKS_DB_COMPRESSION_TYPE: ""
    QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://host.minikube.internal:5432/dtrack"
    QUARKUS_DATASOURCE_USERNAME: "dtrack"
    QUARKUS_DATASOURCE_PASSWORD: "dtrack"
