on:
  workflow_call:
    inputs:
      module:
        type: string
        required: true
        description: "Name of the Maven module to test"

jobs:
  test-native-image:
    name: Test Native Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '17'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Native Image
      run: |-
        mvn -pl commons,${{ inputs.module }} clean install -Pnative -DskipTests
    - name: Test Native Image
      run: |-
        mvn -pl ${{ inputs.module }} test-compile failsafe:integration-test -Pnative