name: Build Native Vulnerability Analyzer

on:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/_build-native-meta.yml"
    - ".github/workflows/build-native-notification-publisher.yml"
    - "commons/**"
    - "vulnerability-analyzer/**"
    - "pom.xml"
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/_build-native-meta.yml
    with:
      module: vulnerability-analyzer
