name: Build Native Metrics Service

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/_build-native-meta.yml"
      - ".github/workflows/build-native-metrics-service.yml"
      - "commons/**"
      - "metrics-service/**"
      - "pom.xml"
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/_build-native-meta.yml
    with:
      module: metrics-service