name: Build Native Notification Publisher

on:
  push:
    branches:
    - main
    paths:
    - ".github/workflows/_build-native-meta.yml"
    - ".github/workflows/build-native-notification-publisher.yml"
    - "commons/**"
    - "commons-persistence/**"
    - "notification-publisher/**"
    - "pom.xml"
    - "proto/**"
  release:
    types:
    - released
  workflow_dispatch: { }

permissions: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-build:
    uses: ./.github/workflows/_build-native-meta.yml
    with:
      module: notification-publisher
    permissions:
      packages: write # Required to push images to ghcr.io
