name: Deploy Documentation

on:
  push:
    paths:
      - "docs/**"
      - mkdocs.yml
    branches:
      - main

permissions: { }

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases
    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # tag=v4.7.0
        with:
          python-version: "3.9"
          check-latest: true
      - name: Install Requirements
        run: pip install mkdocs-material mike
      - name: Determine Project Version
        id: determine_version
        run: |-
          VERSION=`yq -p=xml '.project.version' pom.xml`
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Configure Git User
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Deploy
        run: mike deploy --push --update-aliases ${{ steps.determine_version.outputs.version }} latest