name: Deploy Documentation

on:
  push:
    paths:
      - "docs/**"
      - mkdocs.yml
    branches:
      - main
  release:
    types:
    - released

permissions: { }

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases
    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # tag=v4.7.1
        with:
          python-version: "3.9"
          check-latest: true
      - name: Install Requirements
        run: pip install mkdocs-material mike
      - name: Determine Project Version
        id: determine_version
        run: |-
          VERSION=`yq -p=xml '.project.version' pom.xml`
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Configure Git User
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Deploy
        run: mike deploy --push --update-aliases ${{ steps.determine_version.outputs.version }} latest