name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      Locale:
        description: 'Select the Locale to be used for E2E Testing'
        required: true
        default: 'en'
        type: choice
        options:
          - en
          - de
          - es
          - fr
          - hi
          - it
          - ja
          - pl
          - pt-BR
          - pt
          - ru
          - uk-UA
          - zh
  schedule:
    - cron: "0 0,10,15,20 * * *"

jobs:
  run-playwright-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Hier muss Dependency Track in all ihrer Pracht gestartet werden

      - name: Set the Locale as an environment variable
        run: |
          echo "LOCALE=${{ github.event.inputs.Locale || 'en' }}" >> $GITHUB_ENV

      - name: Generate Random UUID for password use
        run: echo "RANDOM_PASSWORD=$(uuidgen -r)" >> $GITHUB_ENV

      - name: Install necessary dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: playwright-test-results/allure-results

  publish-results:
    needs: run-playwright-e2e
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: playwright-results
          path: playwright-test-results/allure-results

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: allure-report # branch-name to copy history from
          path: latest-test-results

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          gh_pages: latest-test-results
          allure_history: allure-history # directory to publish
          allure_results: playwright-test-results/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure-report # branch-name to paste history to
          publish_dir: allure-history # directory to publish
          # destination_dir: docs/allure/ # directory to publish into
