name: E2E

on:
  push:
    branches:
    - e2e-docker-host
  # As e2e tests depend on the latest container images,
  # only trigger them after building the images completed.
#  workflow_run:
#    workflows:
#    - "Publish Jar"
#    types:
#    - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # The workflow completion event will be triggered for both
    # failures and successes, so we need to check the status.
    # https://github.com/orgs/community/discussions/26238
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test
      run: mvn -pl e2e clean verify -Pe2e-all
