name: Helm CI

on:
  pull_request:
    branches:
    - main
    paths:
    - helm-charts/**

permissions: { }

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # tag=v4.1.1
    - name: Set up Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
    - name: Set up Python
      uses: actions/setup-python@b64ffcaf5b410884ad320a9cfac8866006a109aa # tag=v4.8.0
      with:
        python-version: "3.9"
        check-latest: true
    - name: Set up Chart Testing
      uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # tag=v2.6.1
    - name: Lint Chart
      run: |-
        ct lint --charts ./helm-charts/hyades
