name: Helm CI

on:
  pull_request:
    branches:
    - main
    paths:
    - helm-charts/**

permissions: { }

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout Repository
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # tag=v4.1.0
    - name: Set up Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
    - name: Set up Python
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # tag=v4.7.1
      with:
        python-version: "3.9"
        check-latest: true
    - name: Set up Chart Testing
      uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # tag=v2.4.0
    - name: Lint Chart
      run: |-
        ct lint --charts ./helm-charts/hyades
