name: Helm CI

on:
  pull_request:
    branches:
    - main
    paths:
    - helm-charts/**

permissions: { }

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout Repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # tag=v3.5.3
    - name: Set up Helm
      uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # tag=v3.5
    - name: Set up Python
      uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # tag=v4.7.0
      with:
        python-version: "3.9"
        check-latest: true
    - name: Set up Chart Testing
      uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # tag=v2.4.0
    - name: Lint Chart
      run: |-
        ct lint --charts ./helm-charts/hyades
