name: Publish Vulnerability Analyzer Native Binary

on:
  push:
    branches: [ "native-arm64" ]

jobs:
  build-native-image:
    name: Build Native Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
        - amd64
        - arm64
      fail-fast: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
      with:
        install: true
    - name: Build Native Image
      run: |-
        mvn clean package -Pnative -pl commons,vulnerability-analyzer -DskipTests \
          -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 \
          -Dquarkus.native.container-runtime-options='--platform=linux/${{ matrix.arch }}'
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: native-image-${{ matrix.arch }}
        path: |-
          vulnerability-analyzer/target/*-runner

  build-container-image:
    name: Build Container Image
    runs-on: ubuntu-latest
    needs:
    - build-native-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Download amd64 Binary
        uses: actions/download-artifact@v3.0.2
        with:
          name: native-image-amd64
          path: vulnerability-analyzer/target/amd64
      - name: Download arm64 Binary
        uses: actions/download-artifact@v3.0.2
        with:
          name: native-image-arm64
          path: vulnerability-analyzer/target/arm64
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Container Image
        uses: docker/build-push-action@v3
        with:
          context: ./vulnerability-analyzer
          file: ./vulnerability-analyzer/src/main/docker/Dockerfile.native-multiarch
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/vulnerability-analyzer:native-mutliarch
