name: Publish

on:
  push:
    branches: [ "feature/helmCharts" ]

jobs:
  publish-container-image:
    name: Publish Container Images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1
      with:
        install: true
    - name: Docker login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push
      run: |-
        mvn clean install -DskipTests \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.registry=ghcr.io \
          -Dquarkus.container-image.group=${{ github.repository_owner }} \
          -Dquarkus.container-image.additional-tags=latest \
          -Dquarkus.docker.buildx.platform=linux/amd64,linux/arm64
