name: Publish Repo Meta Analyzer Native Binary

on:
  push:
    branches: [ "main" ]

jobs:
  publish-container-image:
    name: Publish Native Binary based Container Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build native binary
        run: |-
          mvn clean package -Pnative -pl commons,repository-meta-analyzer -DskipTests \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: ./repository-meta-analyzer
          file: ./repository-meta-analyzer/src/main/docker/Dockerfile.native-micro
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/repository-meta-analyzer:latest-native
