name: Publish Native Binary

on:
  push:
    branches: [ "feature/trygraal" ]

jobs:
  publish-container-image:
    name: Publish Native Binary based Container Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
        with:
          install: true
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish native binary for vulnerability analyzer
        run: |-
          mvn clean package -Pnative -pl commons,vulnerability-analyzer -DskipTests \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.tag=latest-test \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.name=vulnerability-analyzer-1.0.0-runner \
            -Dquarkus.container-image.registry=ghcr.io \
            -Dquarkus.container-image.group=${{ github.repository_owner }} 
