# This file is part of Dependency-Track.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) OWASP Foundation. All Rights Reserved.
name: Update Protobuf Documentation

on:
  push:
    branches:
    - main
    paths:
    - "docs/reference/schemas/*.tmpl"
    - "proto/src/main/proto/**/*.proto"
  workflow_dispatch: { }

permissions: { }

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      pull-requests: write
    if: "${{ github.repository_owner == 'DependencyTrack' }}"
    steps:
    - name: Checkout Repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # tag=v4.2.0
    - name: Generate Proto Documentation
      run: ./scripts/gen-proto-docs.sh
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # tag=v7.0.5
      with:
        add-paths: "docs/reference/schemas/*.md"
        branch: update-proto-docs
        body: "Updates Protobuf documentation."
        commit-message: Update proto docs
        delete-branch: true
        labels: documentation
        signoff: true
        title: Update proto docs
